---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      run: website
  replicas: 1
  template:
    metadata:
      labels:
        run: website
    spec:
      containers:
        - name: website
          image: srobo/website
          ports:
            - containerPort: 80
