---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
spec:
  selector:
    matchLabels:
      run: reverse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        run: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: srobo/reverse-proxy
          ports:
            - containerPort: 80
