---
apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    run: website
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
      protocol: TCP
  selector:
    run: website
