---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    run: reverse-proxy
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
      protocol: TCP
  selector:
    run: reverse-proxy
