name: Publish to Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build --tag ${GITHUB_REPOSITORY}/reverse-proxy .

    - name: Log into the Github Docker Registry
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_REGISTRY_TOKEN }}

    - name: Push the Docker image
      run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/reverse-proxy
