name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag {owner}/{repo}:latest

    - name: Build & Push to GitHub Package
      uses: opspresso/action-docker@master
      env:
        REGISTRY: "docker.pkg.github.com"
        TAG_NAME: "latest"
        LATEST: "true"
